version: "3.9"
services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=autos
      - POSTGRES_USER=autos_user
      - POSTGRES_PASSWORD=autos_user
    ports:
      - 5432:5432

  main:
    image: autos
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:postgresql://postgres:5432/autos?allowPublicKeyRetrieval=true&useSSL=false",
            "spring.datasource.username" : "autos_user",
            "spring.datasource.password" : "autos_user",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'